package com.machinarymgmt.service.api.config.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import lombok.Data;

import java.util.List;


@JsonIgnoreProperties(value = "respType", // ignore manually set respType, it will be automatically
    // generated by Jackson during serialization
    allowSetters = true // allows the respType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "respType",
    visible = true)

@Data
public class BaseApiResponse {

  private String respType;

  private Metadata metadata;

  private Status status;

  private List<ApiMessage> messages;

  public BaseApiResponse respType(String respType) {
    this.respType = respType;
    return this;
  }

  public BaseApiResponse metadata(Metadata metadata) {
    this.metadata = metadata;
    return this;
  }

  public BaseApiResponse status(Status status) {
    this.status = status;
    return this;
  }

  public BaseApiResponse messages(List<ApiMessage> messages) {
    this.messages = messages;
    return this;
  }

}

